FROM lambci/lambda:build-nodejs10.x

ENV AWS_DEFAULT_REGION us-east-1
ARG LAMBDA_DEST
ARG CONFIG_FILE_CONTENTS
ENV LAMBDA_DEST $LAMBDA_DEST

WORKDIR /app/

COPY . /app/

RUN npm install && npm prune --production

CMD /app/build_lambda.sh
